org: natatgh
app: graphql-api
service: flask-graphql-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false

package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
