# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: natatgh
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: graphql-api
service: graphql-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    API_KEY: ${env:API_KEY}

functions:
  graphql:
    handler: wsgi.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  wsgi:
    app: app.app
    packRequirements: false

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
    - .pytest_cache/**
    - .serverless/**
    - .idea/**
    - .vscode/**
